NLayerApp.WEB/Models/EmployeeViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace NLayerApp.WEB.Models
{
    public class EmployeeViewModel
    {
        public int Id { get; set; }
        [Required]
        public string FirstName { get; set; }
        [Required]
        public string SecondName { get; set; }
        [Required]
        public string MiddleName { get; set; }
        public DateTime AppliedDate { get; set; }
        [Required]
        public string Position { get; set; }

        public int OrganizationId { get; set; }
    }
}

NLayerApp.WEB/Models/OrganizationViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace NLayerApp.WEB.Models
{
    public class OrganizationViewModel
    {
        public int Id { get; set; }
        [Required]
        public string Name { get; set; }
        public int OrganizationSize { get; set; }
        [Required]
        public string LegalForm { get; set; }
    }
}

NLayerApp.WEB/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLayerApp.BLL.Services;
using NLayerApp.BLL.Interfaces;
using NLayerApp.WEB.Models;
using NLayerApp.WEB.Mappers;

namespace NLayerApp.WEB.Controllers
{
    public class EmployeeController : Controller
    {
        
        private EmployeeService _employeeService;

        public EmployeeController()
        {
            _employeeService = new EmployeeService();
        }

        public ActionResult Index()
        {
            IEnumerable<EmployeeViewModel> employeeViewModels = _employeeService
                .GetEmployees()
                .Select(e => e.ToWebModel());
            return View(employeeViewModels);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(EmployeeViewModel employeeViewModel)
        {
            employeeViewModel.AppliedDate = DateTime.Now;
            _employeeService.CreateEmployee(employeeViewModel.ToBllModel());
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            _employeeService.DeleteEmployee(id);
            return RedirectToAction("Index");
        }
        
        [HttpGet]
        public ActionResult Edit(int id)
        {
            IEnumerable<EmployeeViewModel> employeeViewModels = _employeeService
                .GetEmployees()
                .Select(e => e.ToWebModel());
            EmployeeViewModel employee = employeeViewModels.FirstOrDefault(e => e.Id == id);
            return View(employee);
        }
        [HttpPost]
        public ActionResult Edit(EmployeeViewModel employeeViewModel)
        {
            _employeeService.UpdateEmployee(employeeViewModel.ToBllModel());
            return RedirectToAction("Index");
        }

    }
}

NLayerApp.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NLayerApp.WEB.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

NLayerApp.WEB/Controllers/OrganizationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NLayerApp.BLL.Services;
using NLayerApp.BLL.Interfaces;
using NLayerApp.WEB.Models;
using NLayerApp.WEB.Mappers;

namespace NLayerApp.WEB.Controllers
{
    public class OrganizationController : Controller
    {
        private OrganizationService _organizationService;

        public OrganizationController()
        {
            _organizationService = new OrganizationService();
        }

        // GET: Organization
        public ActionResult Index()
        {
            IEnumerable<OrganizationViewModel> organizationViewModels = _organizationService
                .GetOrganizations()
                .Select(o => o.ToWebModel());
            return View(organizationViewModels);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(OrganizationViewModel organizationViewModel)
        {
            organizationViewModel.OrganizationSize = 0;
            _organizationService.CreateOrganization(organizationViewModel.ToBllModel());
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            _organizationService.DeleteOrganization(id);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            OrganizationViewModel organization = _organizationService
                .GetOrganizations()
                .Select(o => o.ToWebModel())
                .FirstOrDefault(o => o.Id == id);
            return View(organization);
        }
        [HttpPost]
        public ActionResult Edit(OrganizationViewModel organizationViewModel)
        {
            _organizationService.UpdateOrganization(organizationViewModel.ToBllModel());
            return RedirectToAction("Index");
        }

    }
}

NLayerApp.WEB/Views/Employee/Create.cshtml
@model NLayerApp.WEB.Models.EmployeeViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div>
    @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Добавление сотрудника</legend>
            <p>
                Имя:<br />
                @Html.EditorFor(m => m.FirstName)
            </p>
            <p>
                Фамилия:<br />
                @Html.EditorFor(m => m.SecondName)
            </p>
            <p>
                Отчество:<br />
                @Html.EditorFor(m => m.MiddleName)
            </p>
            <p>
                Должность<br />
                @{ 
                    List<SelectListItem> list = new List<SelectListItem>();
                    list.Add(new SelectListItem() { Text = "Разработчик" });
                    list.Add(new SelectListItem() { Text = "Тестировщик" });
                    list.Add(new SelectListItem() { Text = "Бизнес-аналитик" });
                    list.Add(new SelectListItem() { Text = "Менеджер" });
                }
                @Html.DropDownListFor(m => m.Position, list)
            </p>
            <p>
                Id Компании:<br />
                @Html.EditorFor(m => m.OrganizationId)
            </p>
            <p>
                <input type="submit" value="Добавить"/>
            </p>
            
        </fieldset>
    }
</div>
<br />@Html.ActionLink("На главную", "Index", "Home")<br />

NLayerApp.WEB/Views/Employee/Edit.cshtml
@model NLayerApp.WEB.Models.EmployeeViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div>
    @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Редактирование сотрудника</legend>
            <p>
                Имя:<br />
                @Html.EditorFor(m => m.FirstName)
            </p>
            <p>
                Фамилия:<br />
                @Html.EditorFor(m => m.SecondName)
            </p>
            <p>
                Отчество:<br />
                @Html.EditorFor(m => m.MiddleName)
            </p>
            <p>
                Должность<br />
                @{
                    List<SelectListItem> list = new List<SelectListItem>();
                    list.Add(new SelectListItem() { Text = "Разработчик" });
                    list.Add(new SelectListItem() { Text = "Тестировщик" });
                    list.Add(new SelectListItem() { Text = "Бизнес-аналитик" });
                    list.Add(new SelectListItem() { Text = "Менеджер" });
                }
                @Html.DropDownListFor(m => m.Position, list)
            </p>
            <p>
                Id Компании:<br />
                @Html.EditorFor(m => m.OrganizationId)
            </p>
            <p>
                <input type="submit" value="Редактировать" />
            </p>

        </fieldset>
    }
</div>
<br />@Html.ActionLink("На главную", "Index", "Home")<br />

NLayerApp.WEB/Views/Employee/Index.cshtml
@model IEnumerable<NLayerApp.WEB.Models.EmployeeViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Список работников</h2>
<br />
<table>
    <tr>
        <th>№</th>
        <th>Имя</th>
        <th>Фамилия</th>
        <th>Отчество</th>
        <th>Дата приёма</th>
        <th>Должность</th>
        <th>Компания</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelIdem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FirstName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SecondName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MiddleName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AppliedDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Position)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrganizationId)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<br />@Html.ActionLink("На главную", "Index", "Home")<br />

NLayerApp.WEB/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}

<h2>Home page</h2>

<div class="container">
    <div class="col-md-6">
        Работа с сотрудниками:<br />
        @Html.ActionLink("Просмотр всех сотрудников", "Index", "Employee")<br />
        @Html.ActionLink("Добавление нового сотрудника", "Create", "Employee")<br />
    </div>
    <div class="col-md-6">
        Работа с компаниями:<br />
        @Html.ActionLink("Просмотр списка компаний", "Index", "Organization")<br />
        @Html.ActionLink("Добавление новой компании", "Create", "Organization")<br />
    </div>
</div>

NLayerApp.WEB/Views/Organization/Create.cshtml
@model NLayerApp.WEB.Models.OrganizationViewModel
@{
    ViewBag.Title = "Create";
}

<h2>Create organization</h2>

<div>
    @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Добавление компании</legend>
            <p>
                Название:<br />
                @Html.EditorFor(o => o.Name)
            </p>
            <p>
                ОПФ:<br />
                @Html.EditorFor(o => o.LegalForm)
            </p>
            <p>
                <input type="submit" value="Добавить" />
            </p>

        </fieldset>
    }
</div>
<br />@Html.ActionLink("На главную", "Index", "Home")<br />

NLayerApp.WEB/Views/Organization/Edit.cshtml
@model NLayerApp.WEB.Models.OrganizationViewModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit organization</h2>

<div>
    @using (Html.BeginForm())
    {
        <fieldset>
            <legend>Редактирование компании</legend>
            <p>
                Название:<br />
                @Html.EditorFor(o => o.Name)
            </p>
            <p>
                ОПФ:<br />
                @Html.EditorFor(o => o.LegalForm)
            </p>
            <p>
                <input type="submit" value="Редактировать" />
            </p>

        </fieldset>
    }
</div>
<br />@Html.ActionLink("На главную", "Index", "Home")<br />

NLayerApp.WEB/Views/Organization/Index.cshtml
@model IEnumerable<NLayerApp.WEB.Models.OrganizationViewModel>
@{
    ViewBag.Title = "Index";
}

<h2>Список компаний</h2>
<br />
<table>
    <tr>
        <th>№</th>
        <th>Название</th>
        <th>Кол-во сотрудников</th>
        <th>ОПФ</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelIdem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrganizationSize)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.LegalForm)
            </td>
            <td>
                @Html.ActionLink("Редактировать", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Удалить", "Delete", new { id = item.Id })
            </td>
        </tr>
    }
</table>
<br />@Html.ActionLink("На главную", "Index", "Home")<br />

NLayerApp.WEB/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>